### ISSUE TITLE
Managed identity for WebApp has stopped working

### ISSUE THREAD

**Issue by jasond-s** [Azure/azure-sdk#1465]
We have been using `Microsoft.Azure.KeyVault` for some time now with success. Using the managed identity in our WebApps and an AD group to grant access to key vault. The app SP is added to the group and the group has access to key vault, I have tried giving the app direct access rights to KV also, but no help.

I have updated a couple of apps to use the `Azure.Identity` package and the .Net Framework app has continued to operate, but the .Net Core 3.1 app now does not seem to pick up the credentials.

If I add an explicit `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENENT_ID` that corresponds to an RBAC generated service principle, it all works fine. I don't want to have to do this though and would much prefer to use the managed identity (no config floating around).

These are the packages I am now referencing:

    <PackageReference Include="Azure.Identity" Version="1.1.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.3" />

This is the construction code:

    new SecretClient("name-of-vault", new DefaultAzureCredential());

This is the stack trace:

 ---> Azure.Identity.AuthenticationFailedException: DefaultAzureCredential authentication failed.
 ---> Azure.Identity.AuthenticationFailedException: Invalid response, the authentication response was not in the expected format.
   at Azure.Identity.ManagedIdentityClient.Deserialize(JsonElement json)
   at Azure.Identity.ManagedIdentityClient.DeserializeAsync(Stream content, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at Codat.Infrastructure.SecretsProvider.SecretsProvider.<>c__DisplayClass18_0.<<TryGetKeyVaultValue>g__TryGetKeyVaultValue|0>d.MoveNext()

**Comment by jasond-s** [comment]
Moved to SDK for .Net
